name: Primeiro CI

on:
  push:
    branches:
      - master

jobs:
  fisrt-job:
    runs-on: ubuntu-latest

    steps:
      - name: Acesso ao codigo
        uses: actions/checkout@v4

      - name: "Echo Message"
        run: |
          echo "Olá Mundo novamente! Aqui estou!"
          echo "segundo comando"
          pwd
          ls -la ../../

      - name: executa script
        run: bash scripts/info.sh
