name: Primeiro CI

on:
  push:
    branches:
      - master

jobs:
  fisrt-job:
    runs-on: ubuntu-latest

    steps:
      - name: "Echo Message"
        run: |
          echo "Olá Mundo novamente! Aqui estou!"
          echo "segundo comando"
          ip a
